---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: server-1
    box: centos/7
    box_version: 1803.01
    interfaces:
      - virtualbox__intnet: test_network
        network_name: private_network
        ip: 192.168.0.1
    groups:
      - lustre
      - lustre_server
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      # CentOS vagrant boxes seem to be missing the SATA Controller
      - 'customize [ "storagectl", :id, "--name", "SATA Controller", "--add", "SATA", "--controller", "IntelAhci" ]'

      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--type", "dvddrive", "--medium", "emptydrive" ]'

      - 'customize [ "createhd", "--filename", "disk-mgr.vdi" , "--size", "2000", "--format", "VDI" ]'
      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 1, "--type", "hdd", "--medium", "disk-mgr.vdi", "--comment", "This is the Mgr disk" ]'
      - 'customize [ "setextradata", :id, "VBoxInternal/Devices/ahci/0/Config/Port1/SerialNumber", "mgr-1" ]'

      - 'customize [ "createhd", "--filename", "disk-mdt.vdi" , "--size", "2000", "--format", "VDI" ]'
      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 2, "--type", "hdd", "--medium", "disk-mdt.vdi", "--comment", "This is the MDT disk" ]'
      - 'customize [ "setextradata", :id, "VBoxInternal/Devices/ahci/0/Config/Port2/SerialNumber", "mdt-1" ]'

      - 'customize [ "createhd", "--filename", "disk-other.vdi" , "--size", "2000", "--format", "VDI" ]'
      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 7, "--type", "hdd", "--medium", "disk-other.vdi", "--comment", "This is the MDT disk" ]'
      - 'customize [ "setextradata", :id, "VBoxInternal/Devices/ahci/0/Config/Port7/SerialNumber", "other-1" ]'

  - name: oss-1
    box: centos/7
    box_version: 1803.01
    interfaces:
      # - auto_config: true
      #   network_name: private_network
      #   type: dhcp
      - virtualbox__intnet: test_network
        network_name: private_network
        ip: 192.168.0.2
    groups:
      - lustre
      - lustre_oss
    # auto_config: true
    # options:
    #   append_platform_to_hostname: no
    memory: 2048
    cpus: 2
    provider_raw_config_args:
      # CentOS vagrant boxes seem to be missing the SATA Controller
      - 'customize [ "storagectl", :id, "--name", "SATA Controller", "--add", "SATA", "--controller", "IntelAhci" ]'

      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 0, "--type", "dvddrive", "--medium", "emptydrive" ]'

      - 'customize [ "createhd", "--filename", "disk-ost-0.vdi" , "--size", "2000", "--format", "VDI" ]'
      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 10, "--type", "hdd", "--medium", "disk-ost-0.vdi", "--comment", "This is the 1st Object Store disk" ]'
      - 'customize [ "setextradata", :id, "VBoxInternal/Devices/ahci/0/Config/Port10/SerialNumber", "ost-0" ]'

      - 'customize [ "createhd", "--filename", "disk-ost-1.vdi" , "--size", "2000", "--format", "VDI" ]'
      - 'customize [ "storageattach", :id, "--storagectl", "SATA Controller", "--port", 20, "--type", "hdd", "--medium", "disk-ost-1.vdi", "--comment", "This is the 2nd Object Store disk" ]'
      - 'customize [ "setextradata", :id, "VBoxInternal/Devices/ahci/0/Config/Port20/SerialNumber", "ost-1" ]'

  - name: client-1
    box: centos/8
    box_version: 2011.0
    interfaces:
      - virtualbox__intnet: test_network
        network_name: private_network
        ip: 192.168.0.3
    groups:
      - lustre
      - lustre_client
    # auto_config: true
    memory: 2048
    cpus: 2
  - name: client-2
    box: centos/8
    box_version: 2011.0
    interfaces:
      # - auto_config: true
      #   network_name: private_network
      #   type: dhcp
      - virtualbox__intnet: test_network
        network_name: private_network
        ip: 192.168.0.4
    groups:
      - lustre
      - lustre_client
    # auto_config: true
    # options:
    #   append_platform_to_hostname: no
    memory: 2048
    cpus: 2
provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
      stdout_callback: yaml
  inventory:
    group_vars:
      lustre:
        lustre_fsname: lustre
    host_vars:
      server-1:
        lustre_mgt_devs:
          - name: mgr
            serial: mgr-1
        lustre_mdt_devs:
          - name: mdt
            serial: mdt-1
            index: 0
      oss-1:
        lustre_oss_devs:
          - name: ost0
            serial: ost-0
            index: 0
          - name: ost1
            serial: ost-1
            index: 1
verifier:
  name: ansible
